CFLAGS=-Wall -Wextra  -Wfloat-equal -pedantic  -ansi -lm -fsanitize=undefined -fsanitize=address -g3 
CC=gcc
$(MAKECMDGOALS) : $(MAKECMDGOALS).c
	$(CC)  $(MAKECMDGOALS).c $(CFLAGS) -o $(MAKECMDGOALS)
